extends Node

signal update_inventory
signal item_clicked
signal item_right_clicked
signal breakable_clicked
signal ten_seconds_passed
signal overworld_message
signal swap_clicked_in_battle
signal pkmn_go
signal stat_clicked
